language: rust
rust: [nightly-2019-10-04]
cache: cargo
env:
  matrix:
    - RELEASE_FLAG=""
    - RELEASE_FLAG="--release"

install:
  - "export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo \"-Z external-macro-backtrace\")"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f1)"

script:
  - cargo fmt -- --check
  - cargo check --verbose $RELEASE_FLAG
  - cargo build --verbose $RELEASE_FLAG
  - cargo test --verbose $RELEASE_FLAG
  - cargo doc --verbose $RELEASE_FLAG
  - cd testcrate && cargo fmt -- --check
  - cargo check --verbose $RELEASE_FLAG
  - cargo build --verbose $RELEASE_FLAG
  - cargo test --verbose $RELEASE_FLAG
  - cargo doc --verbose $RELEASE_FLAG

after_success:
  - git clone https://${GH_TOKEN}@github.com/SOF3/dirmod.git --branch=gh-pages $HOME/gh-pages
  - cp -r target/doc/* $HOME/gh-pages
  - cd $HOME/gh-pages
  - git config user.name "Travis-CI: cargo doc"
  - git config user.email "sofe2038@gmail.com"
  - git add .
  - git commit -m "Travis-CI doc build: $TRAVIS_COMMIT_MESSAGE"
  - git push -u origin gh-pages
