version: 1
update_configs:
  - package_manager: rust:cargo
    directory: /
    update_schedule: live
    default_labels: ["dependabot", "rust-deps"]
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
